DROP SEQUENCE BRD_NOTICE;
DROP TABLE BRD_NOTICE;

CREATE SEQUENCE BRD_NOTICESEQ;

CREATE TABLE BRD_NOTICE(
	ARTICLE_NO NUMBER PRIMARY KEY,
	NICK VARCHAR2(20) NOT NULL,
	TITLE VARCHAR2(500) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	REGDATE DATE NOT NULL,
	HIT NUMBER NOT NULL
);

INSERT INTO BRD_NOTICE
VALUES (BRD_NOTICESEQ.NEXTVAL, '관리자', 'test', '내용내용', SYSDATE, BRD_NOTICESEQ.NEXTVAL);

SELECT ARTICLE_NO, NICK, TITLE, CONTENT, REGDATE, HIT
FROM BOARD
ORDER BY SEQ DESC;
