DROP SEQUENCE ALL_BOARD;
DROP TABLE SEQUENCE ALL_BOARDSEQ;

CREATE SEQUENCE ALL_BOARDSEQ;

CREATE TABLE ALL_BOARD(
	ARTICLE_NO NUMBER PRIMARY KEY,
	BRD_NO NUMBER NOT NULL,
	ADMIN_WRITER VARCHAR2(400),
	MEM_WRITER VARCHAR2(400),
	TITLE VARCHAR2(1000) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	REGDATE DATE NOT NULL,
	HIT NUMBER NOT NULL
);

INSERT INTO ALL_BOARD
VALUES (ALL_BOARDSEQ.NEXTVAL, 1, '관리자', '사용자', 'BRD_NO 1의 공지 예시 제목', 'BRD_NO 1의 공지 예시 본문', SYSDATE, 1);

INSERT INTO ALL_BOARD
VALUES (ALL_BOARDSEQ.NEXTVAL, 2, '관리자', '사용자', 'BRD_NO 2의 공지 예시 제목', 'BRD_NO 2의 입양대기 예시 본문', SYSDATE, 1);

INSERT INTO ALL_BOARD
VALUES (ALL_BOARDSEQ.NEXTVAL, 3, '관리자', '사용자', 'BRD_NO 3의 공지 예시 제목', 'BRD_NO 3의 입양후기 예시 본문', SYSDATE, 1);

SELECT * FROM ALL_BOARD