DROP SEQUENCE ALL_BOARDSEQ;
DROP TABLE ALL_BOARD;

CREATE SEQUENCE ALL_BOARDSEQ;

CREATE TABLE ALL_BOARD(
	ARTICLE_NO NUMBER PRIMARY KEY,
	BRD_NO NUMBER NOT NULL,
	MEM_NO NUMBER NOT NULL,
	TITLE VARCHAR2(1000) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	REGDATE DATE NOT NULL,
	HIT NUMBER,
	IMAGE VARCHAR2(4000)
	
);

--CONSTARAINT MEM_NO_FK FOREIGN KEY(MEM_NO) REFERENCES LOGINBOARD(MEM_NO) ON DELETE CASCADE
--ARTICLE_NO, BRD_NO, MEM_NO, TITLE, CONTENT, REGDATE,HIT, IMAGE 

--BRD_NO : 1 공지 2 입양대기 3 입양후기 4 Q&A

INSERT INTO ALL_BOARD
VALUES (ALL_BOARDSEQ.NEXTVAL, 1, 3, '공지글시작', '공지글을 한번 작성해봤어요',SYSDATE, 1,NULL);

INSERT INTO ALL_BOARD
VALUES (ALL_BOARDSEQ.NEXTVAL, 2, 3, '입양대기글시작', '입양대기글을 한번 작성해봤어요',SYSDATE, 1,NULL);

INSERT INTO ALL_BOARD
VALUES (ALL_BOARDSEQ.NEXTVAL, 3, 3, '입양후기글시작', '입양후기글을 한번 작성해봤어요',SYSDATE, 1,NULL);

INSERT INTO ALL_BOARD
VALUES (ALL_BOARDSEQ.NEXTVAL, 4, 3, '질문글시작', '질문글을 한번 작성해봤어요',SYSDATE, 1,NULL);

INSERT INTO ALL_BOARD
VALUES (ALL_BOARDSEQ.NEXTVAL, 3, 10, '입양후기글2', '후기글 한번 작성해봤어요',SYSDATE, 1,NULL);

SELECT * FROM ALL_BOARD
ORDER BY ARTICLE_NO DESC;