DROP SEQUENCE BOARD;
DROP TABLE BOARD;

CREATE SEQUENCE BOARDSEQ;

CREATE TABLE BOARD(
	BRD_NO NUMBER NOT NULL,
	BOARDNAME VARCHAR(400) NOT NULL
);

INSERT INTO BOARD
VALUES (5, 'QNA 게시판');

SELECT * FROM BOARD
ORDER BY BRD_NO;
