DROP SEQUENCE BRD_NO;
DROP TABLE BRD_NO;

CREATE SEQUENCE BRD_NOSEQ;

CREATE TABLE BRD_NO(
	NOTICEBOARD NUMBER NOT NULL,
	WAITPETBOARD NUMBER NOT NULL,
	PETBOARD NUMBER NOT NULL,
	ADOPTBOARD NUMBER NOT NULL,
	QNABOARD NUMBER NOT NULL	
);

INSERT INTO BRD_NO
VALUES (1, 2, 3, 4, 5);

SELECT * FROM BRD_NO
