DROP SEQUENCE DONATESEQ;
DROP TABLE DONATE;

CREATE SEQUENCE DONATESEQ;

CREATE TABLE DONATE(
	DONATE_NO NUMBER PRIMARY KEY,
	DONATE_NAME VARCHAR2(20) NOT NULL,
	DONATE_TYPE VARCHAR2(20) NOT NULL,
	DONATE_DATE DATE NOT NULL
);

SELECT DONATE_NO, DONATE_NAME, DONATE_TYPE, DONATE_DATE
FROM DONATE
ORDER BY DONATE_NO DESC;