DROP SEQUENCE PETBOARD;
DROP TABLE PETBOARD;

CREATE SEQUENCE PETBOARDSEQ;

CREATE TABLE PETBOARD(
	ARTICLE_NO NUMBER PRIMARY KEY,
	BRD_NO NUMBER NOT NULL,
	MEM_WRITER VARCHAR2(400) NOT NULL,
	PET_TITLE VARCHAR2(1000) NOT NULL,
	PET_CONTENT VARCHAR2(4000) NOT NULL,
	PET_REGDATE DATE NOT NULL,
	PET_HIT NUMBER NOT NULL
);

INSERT INTO PETBOARD
VALUES (PETBOARDSEQ.NEXTVAL, 2, '유저', '제목제목', '내용내용', SYSDATE, 1);

SELECT ARTICLE_NO, MEM_WRITER, PET_TITLE, PET_CONTENT, PET_REGDATE, PET_HIT
FROM PETBOARD
ORDER BY ARTICLE_NO DESC