DROP SEQUENCE LOGINSEQ;
DROP TABLE LOGINBOARD;

CREATE SEQUENCE LOGINSEQ;


CREATE TABLE LOGINBOARD(
	MEM_NO NUMBER PRIMARY KEY,
	MEM_ID VARCHAR2(20) NOT NULL,
	MEM_PW VARCHAR2(20) NOT NULL,
	MEM_NAME VARCHAR2(20) NOT NULL,
	MEM_NICKNAME VARCHAR2(20) NOT NULL,
	MEM_PHONE VARCHAR2(30) NOT NULL,
	MEM_EMAIL VARCHAR2(30) NOT NULL,
	MEM_ADDR VARCHAR2(2000) NOT NULL,
	MEM_ENABLED VARCHAR2(2) NOT NULL, 
	MEM_ROLE VARCHAR2(100) NOT NULL,
	MEM_IMAGE VARCHAR2(200),	
	
	
	CONSTRAINT MEM_ID_UQ UNIQUE(MEM_ID),
	CONSTRAINT MEM_PHONE_UQ UNIQUE(MEM_NAME),
	CONSTRAINT MEM_EMAIL_UQ UNIQUE(MEM_EMAIL),
	CONSTRAINT MEM_NICK_UQ UNIQUE(MEM_NICKNAME),
	CONSTRAINT MEM_ENABLED_CHK CHECK(MEM_ENABLED IN('Y','N'))
	
);


INSERT INTO LOGINBOARD
VALUES(LOGINSEQ.NEXTVAL,'chacha','1004','차가람','차차','010-7332-6233','부천시','angel@user.com','Y','ADMIN',NULL);

INSERT INTO LOGINBOARD
VALUES(LOGINSEQ.NEXTVAL,'bong','0000','최봉준','봉봉','010-1244-5678','신대봉','bong@user.com','Y','USER',NULL);


SELECT MEM_NO, MEM_ID, MEM_PW, MEM_NAME,MEM_NICKNAME , MEM_PHONE, MEM_ADDR, MEM_EMAIL, MEM_ENABLED,MEM_ROLE, MEM_IMAGE
FROM LOGINBOARD
ORDER BY MEM_NO DESC;